export const products=[
{id:1,
img:"../../../pic.png",
link:"http://lama.dev"
},
{
    id:1,
    img:"https://omde-poshak.ir/pics/picpic.png",
    link:"http://lama.dev"
}
,
{
    id:1,
    img:"https://omde-poshak.ir/pics/picpic.png",
    link:"http://lama.dev"
},
{
    id:1,
    img:"https://omde-poshak.ir/pics/picpic.png",
    link:"http://lama.dev"
},
{
    id:1,
    img:"https://omde-poshak.ir/pics/picpic.png",
    link:"http://lama.dev"
},
{
    id:1,
    img:"https://omde-poshak.ir/pics/picpic.png",
    link:"http://lama.dev"
},

];